#!/bin/bash

# Переменные
SOURCE_FILE="task2.cpp"  # Имя исходного файла программы
OUTPUT_FILE="omptest"  # Имя для скомпилированного исполнимого файла
RESULTS_FILE="results.csv"  # Имя файла для сохранения результатов

# Проверка существования исходного файла
if [ ! -f "$SOURCE_FILE" ]; then
    echo "Ошибка: файл '$SOURCE_FILE' не существует."
    exit 1
fi

# Компиляция программы с OpenMP
echo "Компиляция файла $SOURCE_FILE..."
clang++ -Xclang -fopenmp -std=c++17 -L/opt/homebrew/opt/libomp/lib -I/opt/homebrew/opt/libomp/include -lomp "$SOURCE_FILE" -o "$OUTPUT_FILE"

# Проверка на успешность компиляции
if [ $? -ne 0 ]; then
    echo "Ошибка: компиляция не удалась."
    exit 1
fi

# Очистка старых результатов
rm -f $RESULTS_FILE

# Запись заголовка в CSV файл
echo "GridSize,Processes,ExecutionTime" > $RESULTS_FILE

# Размеры сетки
GRID_SIZES=(10 100 1000 2000 3000)

# Точность
EPSILON=0.0001

# Количество потоков для OpenMP
THREADS=(2 4 6)

# Запуск программы с разными параметрами (сетка и количество потоков)
for GRID in "${GRID_SIZES[@]}"; do
    for THREAD in "${THREADS[@]}"; do
        echo "Запуск программы для сетки размером $GRID с $THREAD потоками..."

        # Запуск программы и извлечение времени выполнения
        OUTPUT=$("./$OUTPUT_FILE" $GRID $EPSILON $THREAD)

        # Извлечение времени выполнения из вывода программы
        TIME=$(echo "$OUTPUT" | grep "Execution time:" | awk '{print $3}')

        # Запись результатов в CSV файл
        echo "$GRID,$THREAD,$TIME" >> $RESULTS_FILE
    done
done

echo "Результаты сохранены в файл $RESULTS_FILE"
